### ISSUE TITLE
Custom Vocabulary

### ISSUE THREAD

**Issue by bharat-patidar** [at16k/at16k#10]
Hi Mohit,

I want to add custom vocabulary to transcribe some specific words. What would you suggest on this?
Do I need to fine tune this model on new training data which include these words or do we have any flexibility with tensor2tensor where we don't need to retrain acoustic model (like kaldi) and just updating the Language model would solve the purpose.
Apologies if this question sounds silly, I am very new to this tensor2tensor library.

Thank you :)

**Comment by mohitsshah** [comment]
At the moment, tensor2tensor does not support adding a custom language model during the decoding process. We can take a look at it once this feature is available.
