### ISSUE TITLE
training code

### ISSUE THREAD

**Issue by cogmeta** [at16k/at16k#3]
Any plans to release the training code or the the details of the architecture?

**Comment by mohitsshah** [comment]
The model is a transformer based architecture trained using the Tensor2Tensor library.

**Comment by cogmeta** [comment]
Thanks. What kind of data was used for the released pre-trained models? How many hours of data?

**Comment by cogmeta** [comment]
we have not yet deep dived into the code so just a quick question: is there a way to insert custom language model  for decoding?

**Comment by mohitsshah** [comment]
It's a mix of openly available datasets (Common Voice, TED-LIUM) and a lot of proprietary data we've collected over the past 2 years. In terms of hours, it's close to ~10000 hours of English language speech.

**Comment by mohitsshah** [comment]
> we have not yet deep dived into the code so just a quick question: is there a way to insert custom language model for decoding?

This is something we're looking into atm. The challenge here is how to integrate the external LM within Tensor2Tensor.

**Comment by cogmeta** [comment]
Awesome! Thank you.  T2T is the only framework we have not yet looked at. Let us see whether we can contribute something at least on integrating LM front.

**Comment by mohitsshah** [comment]
Looking forward to your contribution. Thanks!
