### ISSUE TITLE
Original checkpoint and hparams

### ISSUE THREAD

**Issue by bedapudi6788** [at16k/at16k#7]
@mohitsshah can you provide the training checkpoint and hparams of the tensor2tensor model.

I am working on accessing the beam search results (to see if adding language model scoring improves the result). Although I might be able to access the beam results by finding the node before decoding, it will be much easier if original checkpoint and hparams are there.

**Comment by bedapudi6788** [comment]
Also, it would help anyone looking to fine-tune the model.

**Comment by mohitsshah** [comment]
I'll share the files by the weekend. Would be really helpful to have an external LM. What kind of an LM are you thinking of? RNN-based or something similar to KenLM?

**Comment by bedapudi6788** [comment]
My idea is to make the lm configurable. My current idea is, get 4 beams (this number will be configurable) for the input and re-rank them using lm. (in the final implementation, users should be able to pass their own lm or use pre-provided lms like kenlm or flair for re-scoring)

Of course, I am going to experiment with multiple other ways and see which one gives the best wer on the test set I have.

After you share the training files, I will make colab notebooks with all the lm integration ideas i have. We can evaluate that and add it into this project.

**Comment by bedapudi6788** [comment]
@mohitsshah sorry for nagging. any update on this?

**Comment by mohitsshah** [comment]
@bedapudi6788 apologies for the delay. Here's the link (for the 16K version): https://storage.googleapis.com/at16k-ce/models/t2t.tar.gz

**Comment by bedapudi6788** [comment]
@mohitsshah thank you. I am closing this issue. I will let you know the results of my experiment in a separate issue.

**Comment by bedapudi6788** [comment]
@mohitsshah can you also post the version of tensor2tensor used for training.

**Comment by mohitsshah** [comment]
1.14

**Comment by bedapudi6788** [comment]
```
t2t-exporter --problem=librispeech \
--model=transformer \
--hparams_set=transformer_librispeech_tpu \
--hparams="max_length=295650,max_input_seq_length=3650,max_target_seq_length=250,batch_size=6" \
--data_dir=./t2t \
--output_dir=./t2t
```

@mohitsshah I am trying to generate new exported model using the above command. This fails with

```
INFO:tensorflow:Restoring parameters from ./t2t/model.ckpt-500000
I0326 09:54:53.791654 139772535633792 saver.py:1280] Restoring parameters from ./t2t/model.ckpt-500000
2020-03-26 09:54:54.302423: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1412] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.
2020-03-26 09:54:54.320250: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key transformer/symbol_modality_256_384/shared/weights_0 not found in checkpoint
Traceback (most recent call last):
```

Is this because, the problem ```at16k_subword``` has different architecture than librispeech? 

Tested at: https://colab.research.google.com/drive/1RUjEYY9uE-C0DVsoLhpk86uZ61gNUIIA

**Comment by mohitsshah** [comment]
The architecture only differs in terms of the output modality. Librispeech generates characters at the output, while at16k generates subword units. I'll post the source code for our custom problem in a separate repository within a day.

**Comment by bedapudi6788** [comment]
Thought so. I expected to get a dimension miss match error for the last
layer, as the vocab is different. Instead of that, I got a variable name
not matching.

Anyway, I will reattempt the experiment with your custom problem added to
registry.

Thank you.

**Comment by mohitsshah** [comment]
@bedapudi6788 Just setup the repo. [Here's the link](https://github.com/at16k/at16k-t2t-helpers). Hope this helps.

**Comment by bedapudi6788** [comment]
@mohitsshah it worked. I got the new model with beam search enabled.

**Comment by bedapudi6788** [comment]
beam_width=4 results for test_16k.wav
```
['welcome to the first ever recorded conference thank you', 'welcome to the first ever-recorded conference thank you', 'welcome to the first ever record at conference thank you', 'welcome to the first ever record conference thank you'] [-0.5054556131362915, -1.6241230964660645, -1.8558109998703003, -2.0382258892059326]
```

**Comment by bedapudi6788** [comment]
@mohitsshah I experimented with different beam widths, but didn't notice a major difference in accuracy on real world files. My empirical observation is that, the defaults are pretty good.

Also, note that prediction time is directly proportional to beam width. Since at16k's default prediction time is pretty high, it is not really practical (In my opinion) to run lot of beams and do lm rescoring like kaldi does.

**Comment by bharat-patidar** [comment]
> @mohitsshah it worked. I got the new model with beam search enabled.

Hi @bedapudi6788:
Can you please provide your Colab notebook which you have created to enable beam search?
It would help me to quick-start in the same line.

Thanks!
