### ISSUE TITLE
Max duration limitation

### ISSUE THREAD

**Issue by bharat-patidar** [at16k/at16k#8]
Hi Mohit,
Thanks for sharing your work.

I just wanted to check if there is any workaround or recommended way to avoid the time duration limit.
I was thinking to break audio in segments and then combine using overlapping transcripts.
Would you suggest any better approach than this?

**Comment by mohitsshah** [comment]
At the moment, there is no workaround the duration.
Regarding your approach, overlapping transcripts is not a good idea IMHO. Instead, I would break the audio file into **non-overlapping segments** (using VAD or a turn-based segmentation approach), then run the transcription on each segment independently and finally concatenate the results.

**Comment by bharat-patidar** [comment]
Thanks for the suggestion Mohit!
I tried with VAD, It's working good.
